### ISSUE TITLE
Use arguments to pass the starting hash in from the spec file

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/my-first-hash#2]
To avoid students from copy/pasting the `shipping_manifest` hash from the third or fourth method when solving the second, this should be moved to the spec file and passed into these methods as an argument. Also, the expected key/value pairs might benefit from differing from the example from the lesson, even if they keep with the same theme.

@SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
Hey so this is kind of a contrived example to get them to build/operate on a hash. For the `retrieval` method, it doesn't make sense to pass the hash in as an argument b/c they have to retrieve a specific item from the hash. Do you think it would be okay if I just added a note here and there to the effect of don't copy the below method's content? And the only one they could cheat on is the `shipping_manifest` method.

**Comment by markedwardmurray** [comment]
Sounds good, I did that plenty of times: "don't just hard code the answer!"
